WXDIR = $(WXWIN)

TARGET=xportscan
OBJECTS = $(TARGET).obj
!if "$(WINSOCK1)" == "1"
EXTRALIBS = wsock32 
EXTRACPPFLAGS = -DWINSOCK1
!else
EXTRALIBS = ws2_32
!endif


!if "$(DEBUG)" == "1"
EXTRALINKFLAGS = /Tpe
!endif

!include $(WXDIR)\src\makeprog.b32

