//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: panel.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_panel_H__
#define __WDR_panel_H__

#ifdef __GNUG__
    #pragma interface "panel_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_TEXT 10000
#define TEXT_HOST 10001
#define ID_START 666
#define ID_STOP 911
#define ID_LINE 10002
#define ID_NOTEBOOK 10003
#define PORT_LIST 10004
wxSizer *top_panel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define SCAN_CHOICE 10005
#define PORT_CHOICE 10006
#define START_PORT 10007
#define END_PORT 10008
wxSizer *scan_panel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define SEC_TEXT 10009
#define USEC_TEXT 10010
#define THREAD_TEXT 10011
#define CHECK_THREADS 10012
#define DELAY_TEXT 10013
wxSizer *options_panel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
